# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveform',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='reporing_senior',
            field=models.CharField(choices=[('Badri', 'Badri'), ('Jai Srinivasan', 'Jai Srinivasan')], max_length=30),
        ),
    ]
