# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20180117_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='employee',
        ),
        migrations.AddField(
            model_name='leave',
            name='no_days_or_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
