# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20180117_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('no_days_or_hours', models.IntegerField()),
                ('current_balance', models.FloatField(max_length=10)),
                ('applied', models.IntegerField()),
                ('balance_after_approval', models.IntegerField()),
                ('lop', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='leave',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
