# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leaveform_reporing_senior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveform',
            name='reporing_senior',
        ),
    ]
