# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_remove_leaveform_reporing_senior'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform',
            name='reporing_senior',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
